import { columns } from "./columns";
import { DataTable } from "./data-table";

export default function Table() {
  const data = getData();

  return (
    <div dir="rtl" className="container mx-auto py-10">
      <DataTable data={data} columns={columns} />
    </div>
  );
}

function getData() {
  // Fetch data from your API here.
  return [
    {
      id: "D3699",
      region: "dabaa",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "b4:a9:ab:11:ad:e2",
      ownerName: "الدكتور قحطان آل حسين",
      ownerNumber: "893-743-9130",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2022-08-25T01:34:12",
    },
    {
      id: "D6585",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "dc:01:60:c4:74:3c",
      ownerName: "السيد تحسين آل علي",
      ownerNumber: "(419)622-2769",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-11-03T23:59:19",
    },
    {
      id: "D6309",
      region: "dabaa",
      gate: "iraqGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "68:f3:51:f1:82:22",
      ownerName: "عبد الحقّ آل خضير",
      ownerNumber: "(771)922-1618",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2024-11-13T00:11:40",
    },
    {
      id: "D6759",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "02:30:9f:fe:c9:31",
      ownerName: "الأستاذ شوقي المهنا",
      ownerNumber: "(633)728-3665",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2022-04-13T23:33:42",
    },
    {
      id: "D2100",
      region: "east",
      gate: "saudiGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "58:2d:8d:a4:e1:3c",
      ownerName: "شافع آل رفيع",
      ownerNumber: "(327)214-1902",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2021-05-06T21:30:48",
    },
    {
      id: "D6554",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "fc:55:c5:26:52:1b",
      ownerName: "المهندس يسار حجار",
      ownerNumber: "(369)302-7710",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2023-02-21T10:35:13",
    },
    {
      id: "D3310",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "7c:15:4a:36:58:78",
      ownerName: "السيد عبد الرّشيد المهنا",
      ownerNumber: "(260)624-9525",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2024-05-28T05:51:25",
    },
    {
      id: "D3123",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "20:f4:a9:7c:37:4d",
      ownerName: "الدكتور جلال الحجار",
      ownerNumber: "200-427-7967",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2024-07-08T18:57:21",
    },
    {
      id: "D3954",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "36:9f:a7:fd:ee:df",
      ownerName: "رشاد الشايع",
      ownerNumber: "573-769-7581",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2023-12-16T08:47:05",
    },
    {
      id: "D3536",
      region: "dabaa",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "78:3c:d6:23:d3:b2",
      ownerName: "الدكتور سيف الدّين الحكير",
      ownerNumber: "9765361248",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2023-10-30T08:18:19",
    },
    {
      id: "D5932",
      region: "east",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "88:71:05:38:7f:f2",
      ownerName: "الدكتور حكيم الدباغ",
      ownerNumber: "(226)483-7790",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "24 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2024-12-27T07:49:04",
    },
    {
      id: "D3680",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "8c:d3:ed:ea:2f:1c",
      ownerName: "السيد ضحّاك الشايع",
      ownerNumber: "4812909608",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "24 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2023-03-23T23:19:37",
    },
    {
      id: "D5456",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "d2:ce:fa:ed:7d:2a",
      ownerName: "السيد عبد الإله آل علي",
      ownerNumber: "(673)778-6860",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-08-25T01:05:36",
    },
    {
      id: "D4106",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "bc:21:c7:b8:6b:db",
      ownerName: "صبور المشاولة",
      ownerNumber: "314-961-7360",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2021-01-30T19:20:18",
    },
    {
      id: "D5625",
      region: "lahoon",
      gate: "emaratGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "88:bf:4a:6e:5f:be",
      ownerName: "الدكتور كايد العقيل",
      ownerNumber: "4328420208",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2025-02-27T10:16:16",
    },
    {
      id: "D3835",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "5a:04:26:42:6b:9d",
      ownerName: "الأستاذ مكّي الراشد",
      ownerNumber: "5555502408",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2024-07-07T01:22:10",
    },
    {
      id: "D4835",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "30:59:34:a9:3d:68",
      ownerName: "الأستاذ طارق مهنا",
      ownerNumber: "6639303141",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2024-06-29T08:04:36",
    },
    {
      id: "D2746",
      region: "dabaa",
      gate: "saudiGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "94:56:87:2c:40:21",
      ownerName: "ثاقب العقيل",
      ownerNumber: "5305339459",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2021-12-20T01:56:03",
    },
    {
      id: "D2280",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "64:76:f9:4b:7f:d8",
      ownerName: "زكي الخرافي",
      ownerNumber: "962-463-8983",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "24 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2020-06-13T01:00:43",
    },
    {
      id: "D4662",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "42:5f:68:c4:2b:dd",
      ownerName: "ودود العليان",
      ownerNumber: "(855)476-3091",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2023-07-04T16:57:18",
    },
    {
      id: "D3172",
      region: "lahoon",
      gate: "saudiGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "20:da:14:33:00:7d",
      ownerName: "داوود حنبولي",
      ownerNumber: "986-658-7334",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2021-07-25T00:08:32",
    },
    {
      id: "D6218",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "0c:30:51:e6:da:42",
      ownerName: "السيد كريم آل العسكري",
      ownerNumber: "7152011579",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2021-07-12T03:39:42",
    },
    {
      id: "D6490",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "f2:56:b4:cc:44:0e",
      ownerName: "السيد كليم آل معيض",
      ownerNumber: "8445080283",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2025-01-21T01:16:56",
    },
    {
      id: "D6654",
      region: "dabaa",
      gate: "emaratGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "d6:ef:9b:c7:41:8a",
      ownerName: "الأستاذ هلال آل معيض",
      ownerNumber: "741-307-5246",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2021-03-31T20:47:25",
    },
    {
      id: "D3120",
      region: "east",
      gate: "saudiGate",
      department: "eng",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "82:66:1a:ea:0e:3a",
      ownerName: "المهندس ضرغام آل عطفة",
      ownerNumber: "2387219006",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2021-08-05T02:23:42",
    },
    {
      id: "D5752",
      region: "dabaa",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "a0:1e:5a:01:20:ab",
      ownerName: "المهندس وسيل آل معيض",
      ownerNumber: "6572274150",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2020-12-15T02:18:17",
    },
    {
      id: "D2477",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "1c:9f:d0:95:6c:ab",
      ownerName: "فرزدق آل الشيخ",
      ownerNumber: "7486583250",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-10-30T03:40:00",
    },
    {
      id: "D6960",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "c2:6d:b1:a6:d1:b2",
      ownerName: "مختار الخرافي",
      ownerNumber: "(842)357-1817",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2020-09-30T12:55:46",
    },
    {
      id: "D2045",
      region: "dabaa",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "6e:32:a5:db:53:a7",
      ownerName: "وريد العقيل",
      ownerNumber: "587-906-0272",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2023-01-03T04:06:48",
    },
    {
      id: "D2608",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "b8:f4:96:a6:03:3f",
      ownerName: "السيد رفيق العليان",
      ownerNumber: "444-681-4793",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2024-09-06T01:03:04",
    },
    {
      id: "D2852",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "6a:89:f6:8b:8d:9a",
      ownerName: "السيد ظاعن آل جعفر",
      ownerNumber: "201-408-3217",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2021-04-14T21:48:58",
    },
    {
      id: "D4836",
      region: "lahoon",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "80:c7:df:35:91:1f",
      ownerName: "ميثاق شربتلي",
      ownerNumber: "2253490012",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2022-06-22T04:54:04",
    },
    {
      id: "D6171",
      region: "lahoon",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "ca:83:19:22:08:95",
      ownerName: "السيد قنوع المشاولة",
      ownerNumber: "5726349400",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2023-05-28T00:33:51",
    },
    {
      id: "D6197",
      region: "lahoon",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "6e:ec:d0:36:d3:25",
      ownerName: "الدكتور فخر الدّين الخرافي",
      ownerNumber: "(614)850-3377",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2021-01-08T18:27:15",
    },
    {
      id: "D3597",
      region: "lahoon",
      gate: "emaratGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "f6:e0:f3:91:e2:d0",
      ownerName: "ساهد حجار",
      ownerNumber: "566-423-3748",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2023-07-22T03:47:20",
    },
    {
      id: "D2503",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "90:4c:ca:f0:9a:15",
      ownerName: "المهندس نظام آل حسين",
      ownerNumber: "930-421-4387",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2023-04-08T09:19:36",
    },
    {
      id: "D3365",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "60:51:18:2c:a4:a4",
      ownerName: "نجدت شربتلي",
      ownerNumber: "3836524114",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2022-08-16T10:01:41",
    },
    {
      id: "D2237",
      region: "east",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "46:85:fe:ba:5c:89",
      ownerName: "الدكتور سليمان آل عواض",
      ownerNumber: "9305016771",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2020-07-02T22:52:42",
    },
    {
      id: "D5003",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "6e:75:9b:ec:ae:72",
      ownerName: "الأستاذ هاشم الجفالي",
      ownerNumber: "(549)654-3159",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2024-02-14T08:38:22",
    },
    {
      id: "D6431",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "1c:c8:bc:04:7c:3f",
      ownerName: "الأستاذ مشفق العقيل",
      ownerNumber: "5167905922",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2021-02-11T14:21:54",
    },
    {
      id: "D3682",
      region: "east",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "a0:33:61:c2:56:50",
      ownerName: "رزين آل محمد بن علي بن جماز",
      ownerNumber: "4376766094",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2023-11-16T05:04:07",
    },
    {
      id: "D6562",
      region: "east",
      gate: "saudiGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "00:a5:db:ab:7c:61",
      ownerName: "منتصر آل عايض",
      ownerNumber: "(830)766-2267",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2020-01-12T07:54:14",
    },
    {
      id: "D5475",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "98:f6:ca:1a:82:96",
      ownerName: "الدكتور خالد المغاولة",
      ownerNumber: "(792)218-8133",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2024-10-26T15:59:00",
    },
    {
      id: "D2735",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "a2:c6:dc:56:37:92",
      ownerName: "يقين آل الشيخ",
      ownerNumber: "217-381-0469",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2022-08-12T07:46:10",
    },
    {
      id: "D3579",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "a8:cd:1a:57:60:12",
      ownerName: "الدكتور فخر آل سلطان",
      ownerNumber: "8922128642",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2022-11-26T09:02:43",
    },
    {
      id: "D2026",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "f6:a1:54:6f:76:dd",
      ownerName: "المهندس فكري آل رفيع",
      ownerNumber: "4105396989",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-01-22T04:13:43",
    },
    {
      id: "D4694",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "bc:b0:c7:54:a8:4b",
      ownerName: "السيد مؤنس المغاولة",
      ownerNumber: "(909)577-7615",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2021-07-10T09:13:47",
    },
    {
      id: "D6048",
      region: "dabaa",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "f2:e8:1e:d5:b4:e5",
      ownerName: "سمير آل قصير",
      ownerNumber: "605-514-8615",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2020-08-21T11:25:51",
    },
    {
      id: "D6518",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "ae:33:ba:39:6e:b4",
      ownerName: "عذب بن لادن",
      ownerNumber: "6485736747",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2024-11-28T03:28:38",
    },
    {
      id: "D5383",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "10:88:85:30:d6:36",
      ownerName: "كمال الحكير",
      ownerNumber: "(544)878-7794",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2025-02-27T01:09:41",
    },
    {
      id: "D5735",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "44:4b:b5:de:11:f0",
      ownerName: "المهندس نصر الدّين آل عطفة",
      ownerNumber: "(720)224-4329",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2020-09-24T23:06:23",
    },
    {
      id: "D5206",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "32:df:ff:f3:b6:3d",
      ownerName: "مُنذر آل رفيع",
      ownerNumber: "(515)923-2365",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-04-18T05:34:33",
    },
    {
      id: "D5096",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "78:a1:fd:25:ae:72",
      ownerName: "شكيب آل جعفر",
      ownerNumber: "(615)358-5404",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2022-11-20T23:39:37",
    },
    {
      id: "D4402",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "6c:0e:00:49:1a:0c",
      ownerName: "السيد غزير المهنا",
      ownerNumber: "958-333-3211",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2022-11-29T03:14:08",
    },
    {
      id: "D2774",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "42:c5:5e:1b:d6:0b",
      ownerName: "سعيد العجلان",
      ownerNumber: "(956)526-0627",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2021-08-29T23:17:29",
    },
    {
      id: "D4644",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "8a:b3:7c:ff:b0:82",
      ownerName: "الأستاذ فايد كانو",
      ownerNumber: "6222169297",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2024-10-12T04:55:56",
    },
    {
      id: "D4165",
      region: "dabaa",
      gate: "emaratGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "04:9d:54:b9:ed:fd",
      ownerName: "رحيب آل رفيع",
      ownerNumber: "(672)322-7805",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2023-04-23T08:58:05",
    },
    {
      id: "D5341",
      region: "dabaa",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "7a:b1:35:89:e5:c4",
      ownerName: "السيد عبد القهّار آل خضير",
      ownerNumber: "(509)428-7821",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2020-07-06T17:10:14",
    },
    {
      id: "D3372",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "7e:18:a2:94:29:4c",
      ownerName: "الأستاذ سفير حجار",
      ownerNumber: "(958)927-9919",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2024-06-25T12:02:04",
    },
    {
      id: "D2918",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "20:0b:77:ac:8e:2b",
      ownerName: "السيد فاروق المغاولة",
      ownerNumber: "595-443-4337",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2022-01-21T14:51:37",
    },
    {
      id: "D5778",
      region: "dabaa",
      gate: "saudiGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "9c:52:d9:71:8c:35",
      ownerName: "المهندس سالم الجابر",
      ownerNumber: "8222272000",
      cpuType: "AMD",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2023-06-22T03:04:12",
    },
    {
      id: "D5834",
      region: "east",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "94:a8:5b:00:9b:4c",
      ownerName: "نصري آل محمد بن علي بن جماز",
      ownerNumber: "(862)447-5484",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2024-12-05T11:13:01",
    },
    {
      id: "D3785",
      region: "lahoon",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "7e:70:eb:6e:31:24",
      ownerName: "زيد المشاولة",
      ownerNumber: "5576903794",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2024-08-01T14:27:22",
    },
    {
      id: "D5560",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "da:fc:30:d4:ae:6b",
      ownerName: "وثّاب آل رفيع",
      ownerNumber: "850-492-0780",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2024-02-04T12:00:29",
    },
    {
      id: "D5674",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "22:c7:aa:ff:e6:84",
      ownerName: "المهندس علاء الدّين آل عطفة",
      ownerNumber: "(716)761-7078",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2024-10-17T10:42:33",
    },
    {
      id: "D4838",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "d0:66:82:63:6a:47",
      ownerName: "نورس حنبولي",
      ownerNumber: "684-852-9479",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2023-10-25T16:07:11",
    },
    {
      id: "D5721",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "70:c6:ec:51:2a:de",
      ownerName: "شهير مهنا",
      ownerNumber: "3363252441",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2024-03-09T08:02:50",
    },
    {
      id: "D3351",
      region: "lahoon",
      gate: "emaratGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "48:18:a4:22:e9:60",
      ownerName: "مَجدي آل سلطان",
      ownerNumber: "9468444444",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2020-10-06T05:26:23",
    },
    {
      id: "D6929",
      region: "dabaa",
      gate: "emaratGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "f4:14:c1:1e:10:19",
      ownerName: "المهندس مؤيّد آل مقطة",
      ownerNumber: "(985)210-6255",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2021-08-16T04:25:27",
    },
    {
      id: "D6302",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "8a:95:b1:76:f7:2e",
      ownerName: "الأستاذ فوزي الخرافي",
      ownerNumber: "3418385979",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2022-03-23T21:51:42",
    },
    {
      id: "D3982",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "9a:14:17:8f:18:cd",
      ownerName: "الدكتور جمال الدّين الدباغ",
      ownerNumber: "7087850611",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2021-12-19T14:12:30",
    },
    {
      id: "D2217",
      region: "lahoon",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "50:7e:90:47:41:b2",
      ownerName: "الدكتور علاء الدّين المهيدب",
      ownerNumber: "602-832-5833",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2020-07-06T22:18:19",
    },
    {
      id: "D6781",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "ee:e9:9f:a2:80:9d",
      ownerName: "عاصم الراشد",
      ownerNumber: "(664)625-2715",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "4 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2020-08-28T19:19:37",
    },
    {
      id: "D2267",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "42:b2:27:96:fb:67",
      ownerName: "المهندس جرير الدباغ",
      ownerNumber: "788-715-1123",
      cpuType: "AMD",
      cpuModel: "i3",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "24 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2024-04-29T00:36:02",
    },
    {
      id: "D4394",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "b6:33:cb:1f:8e:f6",
      ownerName: "عابد آل عايض",
      ownerNumber: "238-767-3862",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2024-01-07T09:30:25",
    },
    {
      id: "D5374",
      region: "lahoon",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "b2:5e:38:27:6d:1d",
      ownerName: "مؤيّد آل بن ظافر",
      ownerNumber: "731-206-5005",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2020-07-16T10:35:56",
    },
    {
      id: "D2094",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "38:71:81:aa:30:87",
      ownerName: "المهندس مشفق الجفالي",
      ownerNumber: "9512725507",
      cpuType: "AMD",
      cpuModel: "i5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2024-03-18T13:45:49",
    },
    {
      id: "D6267",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "10:0a:71:91:13:08",
      ownerName: "وسيل آل مقطة",
      ownerNumber: "(687)418-3387",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2023-08-01T18:18:44",
    },
    {
      id: "D5338",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "70:5d:6d:63:a5:a8",
      ownerName: "موفّق آل حسين",
      ownerNumber: "8357973293",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2021-01-27T00:29:39",
    },
    {
      id: "D2390",
      region: "dabaa",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "36:7d:8b:57:e3:a5",
      ownerName: "جاسم حنبولي",
      ownerNumber: "675-203-2823",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2023-03-24T00:49:40",
    },
    {
      id: "D5482",
      region: "lahoon",
      gate: "saudiGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "ba:8e:df:23:31:8c",
      ownerName: "وريد مهنا",
      ownerNumber: "996-935-7632",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2022-02-16T13:04:24",
    },
    {
      id: "D5486",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "a6:c6:21:4c:08:78",
      ownerName: "الدكتور صارم آل عواض",
      ownerNumber: "6929111088",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2023-07-16T20:35:06",
    },
    {
      id: "D6955",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "e6:21:4e:dd:b8:7f",
      ownerName: "المهندس عزّت حنبولي",
      ownerNumber: "974-354-0671",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "4 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "HDD",
      createdAt: "2024-04-01T21:52:24",
    },
    {
      id: "D2368",
      region: "dabaa",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "c8:70:97:17:37:60",
      ownerName: "الأستاذ لطفي العجلان",
      ownerNumber: "208-446-0002",
      cpuType: "AMD",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2023-02-28T07:08:19",
    },
    {
      id: "D3349",
      region: "dabaa",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "4c:12:46:36:68:7c",
      ownerName: "مروان مهنا",
      ownerNumber: "6985545976",
      cpuType: "AMD",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "6 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2023-08-29T05:47:36",
    },
    {
      id: "D6341",
      region: "lahoon",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "0e:d5:ff:eb:b5:4f",
      ownerName: "الأستاذ كمال العجلان",
      ownerNumber: "205-610-1510",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثاني",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2024-06-10T20:11:47",
    },
    {
      id: "D2724",
      region: "lahoon",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "9c:10:5c:d4:62:4e",
      ownerName: "السيد نصور آل رفيع",
      ownerNumber: "(939)734-3280",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2022-12-17T01:15:40",
    },
    {
      id: "D5782",
      region: "lahoon",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "0a:10:b6:1b:f4:3b",
      ownerName: "هاني فصيل",
      ownerNumber: "(434)994-8276",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "GTX 1050",
      gpuSize: "24 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
      createdAt: "2025-02-21T01:06:35",
    },
    {
      id: "D3822",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 1",
      macAddress: "9a:a6:30:44:2f:ef",
      ownerName: "مشرق آل الشيخ",
      ownerNumber: "(332)279-8383",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "HDD",
      createdAt: "2022-10-04T11:00:11",
    },
    {
      id: "D5032",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "68:d4:f2:6a:39:f3",
      ownerName: "رضي آل محمد بن علي بن جماز",
      ownerNumber: "(895)758-1537",
      cpuType: "AMD",
      cpuModel: "i5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2022-03-04T23:10:09",
    },
    {
      id: "D6674",
      region: "lahoon",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "1c:70:29:bd:ad:6a",
      ownerName: "يوسف العليان",
      ownerNumber: "(959)925-6481",
      cpuType: "AMD",
      cpuModel: "i7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "RX 5700",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2023-04-17T06:47:27",
    },
    {
      id: "D3608",
      region: "lahoon",
      gate: "iraqGate",
      department: "nozm",
      office: "area",
      deviceType: "جهاز 1",
      macAddress: "b0:17:a2:e7:2c:80",
      ownerName: "المهندس فدائي العجلان",
      ownerNumber: "658-560-0629",
      cpuType: "AMD",
      cpuModel: "i9",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "HDD",
      createdAt: "2023-09-16T23:46:21",
    },
    {
      id: "D2720",
      region: "east",
      gate: "iraqGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "1e:07:a0:20:75:1d",
      ownerName: "معن أبا الخيل",
      ownerNumber: "2979133156",
      cpuType: "انتل",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2023-03-10T04:23:34",
    },
    {
      id: "D5660",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 3",
      macAddress: "bc:cc:11:d5:de:46",
      ownerName: "الأستاذ غسّان العجلان",
      ownerNumber: "(415)503-0287",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RTX 3090",
      gpuSize: "8 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
      createdAt: "2022-04-12T02:50:45",
    },
    {
      id: "D2482",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 2",
      macAddress: "38:dc:55:87:b0:cc",
      ownerName: "جعفر آل عطفة",
      ownerNumber: "900-343-4202",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "4 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2022-09-03T09:27:40",
    },
    {
      id: "D6568",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "40:67:a9:48:d0:67",
      ownerName: "ناعم آل سلطان",
      ownerNumber: "(800)353-3464",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "4 تيرابايت",
      romType: "SSD",
      createdAt: "2022-10-02T23:14:24",
    },
    {
      id: "D4298",
      region: "east",
      gate: "saudiGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "46:14:c3:33:52:04",
      ownerName: "ساجي آل محمد بن علي بن جماز",
      ownerNumber: "4649498922",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "GTX 1660",
      gpuSize: "8 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "HDD",
      createdAt: "2022-04-29T17:49:25",
    },
    {
      id: "D5870",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 3",
      macAddress: "2c:e9:be:c7:8f:8a",
      ownerName: "الأستاذ زاكي كانو",
      ownerNumber: "574-746-0019",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
      createdAt: "2024-12-25T09:02:10",
    },
    {
      id: "D3713",
      region: "lahoon",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "88:b7:ea:62:4d:0d",
      ownerName: "حامد الجفالي",
      ownerNumber: "3326941150",
      cpuType: "انتل",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "6 جيجابايت",
      ramSize: "64 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
      createdAt: "2020-08-12T23:55:03",
    },
    {
      id: "D3036",
      region: "east",
      gate: "emaratGate",
      department: "money",
      office: "deps",
      deviceType: "جهاز 2",
      macAddress: "ea:b2:bf:64:cf:06",
      ownerName: "الدكتور طيّب المشاولة",
      ownerNumber: "615-323-5655",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الرابع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "24 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
      createdAt: "2021-12-28T05:35:27",
    },
  ];
}
