import { columns } from "./columns";
import { DataTable } from "./data-table";

export default function Table() {
  const data = getData();

  return (
    <div dir="rtl" className="container mx-auto py-10">
      <DataTable data={data} columns={columns} />
    </div>
  );
}

function getData() {
  // Fetch data from your API here.
  return [
    {
      id: "D3532",
      region: "dabaa",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "d06af338-0fe9-52a6-94ee-cfd2206fb867",
      ownerName: "نيللي كلارك",
      ownerNumber: "010554622636",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4294",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "35a25314-ae9e-5c23-a9a6-bc35bed120c2",
      ownerName: "ماثيلدا بوب",
      ownerNumber: "010244345463",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D5835",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "64e3b97d-6872-51e9-8f1b-1bb19311066b",
      ownerName: "فرانكلين كانون",
      ownerNumber: "010379968655",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2926",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 4",
      macAddress: "f1132ec9-321c-553d-9168-c36795e82bd5",
      ownerName: "ديل فاسكيز",
      ownerNumber: "010611345722",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4769",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 5",
      macAddress: "11b276df-ce57-5e26-969f-ac03e92da831",
      ownerName: "فلورنس تايلور",
      ownerNumber: "010930146613",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2544",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 6",
      macAddress: "e6a5f97a-6d86-52f7-9280-5f3be38bc5ce",
      ownerName: "آدم لامب",
      ownerNumber: "010804408612",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D3532",
      region: "dabaa",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "d06af338-0fe9-52a6-94ee-cfd2206fb867",
      ownerName: "نيللي كلارك",
      ownerNumber: "010554622636",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4294",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "35a25314-ae9e-5c23-a9a6-bc35bed120c2",
      ownerName: "ماثيلدا بوب",
      ownerNumber: "010244345463",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D5835",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "64e3b97d-6872-51e9-8f1b-1bb19311066b",
      ownerName: "فرانكلين كانون",
      ownerNumber: "010379968655",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2926",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 4",
      macAddress: "f1132ec9-321c-553d-9168-c36795e82bd5",
      ownerName: "ديل فاسكيز",
      ownerNumber: "010611345722",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4769",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 5",
      macAddress: "11b276df-ce57-5e26-969f-ac03e92da831",
      ownerName: "فلورنس تايلور",
      ownerNumber: "010930146613",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2544",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 6",
      macAddress: "e6a5f97a-6d86-52f7-9280-5f3be38bc5ce",
      ownerName: "آدم لامب",
      ownerNumber: "010804408612",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D6543",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 7",
      macAddress: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      ownerName: "سارة أحمد",
      ownerNumber: "010123456789",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7890",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 8",
      macAddress: "b2c3d4e5-f678-90ab-cdef-1234567890ab",
      ownerName: "محمد علي",
      ownerNumber: "010987654321",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D1234",
      region: "dabaa",
      gate: "emaratGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 9",
      macAddress: "c3d4e5f6-7890-abcd-ef12-34567890abcd",
      ownerName: "ليلى حسن",
      ownerNumber: "010112233445",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D5678",
      region: "east",
      gate: "emaratGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 10",
      macAddress: "d4e5f678-90ab-cdef-1234-567890abcdef",
      ownerName: "عمر عبد الله",
      ownerNumber: "010223344556",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D9101",
      region: "lahoon",
      gate: "emaratGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 11",
      macAddress: "e5f67890-abcd-ef12-3456-7890abcdef12",
      ownerName: "فاطمة يوسف",
      ownerNumber: "010334455667",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1121",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 12",
      macAddress: "f67890ab-cdef-1234-5678-90abcdef1234",
      ownerName: "يوسف إبراهيم",
      ownerNumber: "010445566778",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "10 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D3141",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 13",
      macAddress: "67890abc-def1-2345-6789-0abcdef12345",
      ownerName: "هند عبد الرحمن",
      ownerNumber: "010556677889",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D5161",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 14",
      macAddress: "7890abcd-ef12-3456-7890-abcdef123456",
      ownerName: "خالد مصطفى",
      ownerNumber: "010667788990",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7181",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 15",
      macAddress: "890abcdef-1234-5678-90ab-cdef12345678",
      ownerName: "مريم حسين",
      ownerNumber: "010778899001",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D9201",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 16",
      macAddress: "90abcdef-1234-5678-90ab-cdef12345678",
      ownerName: "أحمد عبد العزيز",
      ownerNumber: "010889900112",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1222",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 17",
      macAddress: "abcdef12-3456-7890-abcd-ef1234567890",
      ownerName: "سامي عبد الله",
      ownerNumber: "010990011223",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D3242",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 18",
      macAddress: "bcdef123-4567-890a-bcde-f1234567890a",
      ownerName: "نادية عبد الرحمن",
      ownerNumber: "010001122334",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "10 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D5262",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 19",
      macAddress: "cdef1234-5678-90ab-cdef-1234567890ab",
      ownerName: "علي عبد الكريم",
      ownerNumber: "010112233445",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7282",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 20",
      macAddress: "def12345-6789-0abc-def1-234567890abc",
      ownerName: "منى عبد الله",
      ownerNumber: "010223344556",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D9302",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 21",
      macAddress: "ef123456-7890-abcd-ef12-34567890abcd",
      ownerName: "حسن عبد الرحمن",
      ownerNumber: "010334455667",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1323",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 22",
      macAddress: "f1234567-890a-bcde-f123-4567890abcde",
      ownerName: "سعيد عبد الله",
      ownerNumber: "010445566778",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D3532",
      region: "dabaa",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 1",
      macAddress: "d06af338-0fe9-52a6-94ee-cfd2206fb867",
      ownerName: "نيللي كلارك",
      ownerNumber: "010554622636",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4294",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 2",
      macAddress: "35a25314-ae9e-5c23-a9a6-bc35bed120c2",
      ownerName: "ماثيلدا بوب",
      ownerNumber: "010244345463",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "6 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "256 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D5835",
      region: "dabaa",
      gate: "iraqGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 3",
      macAddress: "64e3b97d-6872-51e9-8f1b-1bb19311066b",
      ownerName: "فرانكلين كانون",
      ownerNumber: "010379968655",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2926",
      region: "east",
      gate: "iraqGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 4",
      macAddress: "f1132ec9-321c-553d-9168-c36795e82bd5",
      ownerName: "ديل فاسكيز",
      ownerNumber: "010611345722",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D4769",
      region: "lahoon",
      gate: "iraqGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 5",
      macAddress: "11b276df-ce57-5e26-969f-ac03e92da831",
      ownerName: "فلورنس تايلور",
      ownerNumber: "010930146613",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D2544",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 6",
      macAddress: "e6a5f97a-6d86-52f7-9280-5f3be38bc5ce",
      ownerName: "آدم لامب",
      ownerNumber: "010804408612",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3090",
      gpuSize: "24 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D6543",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 7",
      macAddress: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      ownerName: "سارة أحمد",
      ownerNumber: "010123456789",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7890",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 8",
      macAddress: "b2c3d4e5-f678-90ab-cdef-1234567890ab",
      ownerName: "محمد علي",
      ownerNumber: "010987654321",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D1234",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 9",
      macAddress: "c3d4e5f6-7890-abcd-ef12-34567890abcd",
      ownerName: "ليلى حسن",
      ownerNumber: "010112233445",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D5678",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 10",
      macAddress: "d4e5f678-90ab-cdef-1234-567890abcdef",
      ownerName: "عمر عبد الله",
      ownerNumber: "010223344556",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D9101",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 11",
      macAddress: "e5f67890-abcd-ef12-3456-7890abcdef12",
      ownerName: "فاطمة يوسف",
      ownerNumber: "010334455667",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1121",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 12",
      macAddress: "f67890ab-cdef-1234-5678-90abcdef1234",
      ownerName: "يوسف إبراهيم",
      ownerNumber: "010445566778",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "10 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D3141",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 13",
      macAddress: "67890abc-def1-2345-6789-0abcdef12345",
      ownerName: "هند عبد الرحمن",
      ownerNumber: "010556677889",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D5161",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 14",
      macAddress: "7890abcd-ef12-3456-7890-abcdef123456",
      ownerName: "خالد مصطفى",
      ownerNumber: "010667788990",
      cpuType: "انتل",
      cpuModel: "i5",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "GTX 1660",
      gpuSize: "6 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7181",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 15",
      macAddress: "890abcdef-1234-5678-90ab-cdef12345678",
      ownerName: "مريم حسين",
      ownerNumber: "010778899001",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثاني",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D9201",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 16",
      macAddress: "90abcdef-1234-5678-90ab-cdef12345678",
      ownerName: "أحمد عبد العزيز",
      ownerNumber: "010889900112",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1222",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 17",
      macAddress: "abcdef12-3456-7890-abcd-ef1234567890",
      ownerName: "سامي عبد الله",
      ownerNumber: "010990011223",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الرابع",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D3242",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 18",
      macAddress: "bcdef123-4567-890a-bcde-f1234567890a",
      ownerName: "نادية عبد الرحمن",
      ownerNumber: "010001122334",
      cpuType: "انتل",
      cpuModel: "i9",
      cpuGeneration: "الجيل العاشر",
      gpuType: "نفيديا",
      gpuModel: "RTX 3080",
      gpuSize: "10 جيجابايت",
      ramSize: "32 جيجابايت",
      ramType: "DDR4",
      romSize: "2 تيرابايت",
      romType: "SSD",
    },
    {
      id: "D5262",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 19",
      macAddress: "cdef1234-5678-90ab-cdef-1234567890ab",
      ownerName: "علي عبد الكريم",
      ownerNumber: "010112233445",
      cpuType: "AMD",
      cpuModel: "Ryzen 5",
      cpuGeneration: "الجيل الثالث",
      gpuType: "نفيديا",
      gpuModel: "GTX 1050",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "512 جيجابايت",
      romType: "SSD",
    },
    {
      id: "D7282",
      region: "lahoon",
      gate: "saudiGate",
      department: "eng",
      office: "abstracts",
      deviceType: "جهاز 20",
      macAddress: "def12345-6789-0abc-def1-234567890abc",
      ownerName: "منى عبد الله",
      ownerNumber: "010223344556",
      cpuType: "انتل",
      cpuModel: "i3",
      cpuGeneration: "الجيل الثامن",
      gpuType: "AMD",
      gpuModel: "RX 580",
      gpuSize: "4 جيجابايت",
      ramSize: "8 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D9302",
      region: "dabaa",
      gate: "saudiGate",
      department: "money",
      office: "area",
      deviceType: "جهاز 21",
      macAddress: "ef123456-7890-abcd-ef12-34567890abcd",
      ownerName: "حسن عبد الرحمن",
      ownerNumber: "010334455667",
      cpuType: "انتل",
      cpuModel: "i7",
      cpuGeneration: "الجيل التاسع",
      gpuType: "نفيديا",
      gpuModel: "RTX 2070",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
    {
      id: "D1323",
      region: "east",
      gate: "saudiGate",
      department: "nozm",
      office: "deps",
      deviceType: "جهاز 22",
      macAddress: "f1234567-890a-bcde-f123-4567890abcde",
      ownerName: "سعيد عبد الله",
      ownerNumber: "010445566778",
      cpuType: "AMD",
      cpuModel: "Ryzen 7",
      cpuGeneration: "الجيل الثالث",
      gpuType: "AMD",
      gpuModel: "RX 5700",
      gpuSize: "8 جيجابايت",
      ramSize: "16 جيجابايت",
      ramType: "DDR4",
      romSize: "1 تيرابايت",
      romType: "HDD",
    },
  ];
}
